namespace LibRender2.Overlays
{
	/// <summary>How the gradient shows.</summary>
	public enum GradientDisplayMode
	{
		/// <summary>Hidden.</summary>
		None = 0,
		/// <summary>Percentage at the current spot.</summary>
		Percentage,
		/// <summary>As N in N.</summary>
		UnitOfChange,
		/// <summary>Per mill.</summary>
		Permil
	}

	/// <summary>How the distance to the next station shows.</summary>
	public enum DistanceToNextStationDisplayMode
	{
		/// <summary>Hidden.</summary>
		None,
		/// <summary>In km.</summary>
		Km,
		/// <summary>In miles.</summary>
		Mile
	}

	/// <summary>Which timetable is on screen.</summary>
	public enum DisplayedTimetable
	{
		/// <summary>None.</summary>
		None = 0,
		/// <summary>Default timetable.</summary>
		Default = 1,
		/// <summary>Custom image.</summary>
		Custom = 2
	}

	/// <summary>How the speed shows.</summary>
	public enum SpeedDisplayMode
	{
		/// <summary>Hidden.</summary>
		None,
		/// <summary>In km/h.</summary>
		Kmph,
		/// <summary>In mph.</summary>
		Mph
	}

	/// <summary>Which timetable to prefer.</summary>
	public enum TimeTableMode
	{
		/// <summary>Off.</summary>
		None = 0,
		/// <summary>Custom first, then auto-generated.</summary>
		Default = 1,
		/// <summary>Only auto-generated.</summary>
		AutoGenerated = 2,
		/// <summary>Auto-generated only when no custom one exists.</summary>
		PreferCustom = 3
	}
}
